//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracker.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public Nullable<int> DeveloperId { get; set; }
    
        public virtual Developer Developers { get; set; }
    }
}
